NAME_TO_TICKER = {
    "Afterpay Limited": "ASX.APT",
    "Altium Limited": "ASX.ALU",
    "Appen Limited": "ASX.APX",
    "Arcadium Lithium PLC": "NYSE.ACY",
    "a2 Milk Co Ltd": "ASX.A2M",
    "Bapcor Ltd": "ASX.BAP",
    "BetaShares Crude Oil Index ETF": "ASX.OOO",
    "BetaShares Global Sustainability Leaders ETF": "ASX.ETHI",
    "BetaShares NASDAQ 100 ETF": "ASX.NDX",
    "BetaShares S&P 500 Yield Maximiser Fund": "ASX.UMAX",
    "Betashares Asia Technology Tigers ETF": "ASX.ASIA",
    "Betashares Crypto Innovators ETF": "ASX.CRYP",
    "Betashares India Quality ETF": "ASX.IIND",
    "Blackmores Limited": "ASX.BKL",
    "Block Inc (AU)": "ASX.XYZ",
    "BWX Limited": "ASX.BWX",
    "Commonwealth Bank of Australia": "ASX.CBA",
    "Flight Centre Travel Group Ltd": "ASX.FLT",
    "Invesco QQQ Trust Series 1 (All Sessions)": "NDQ.QQQ",
    "Jumbo Interactive Ltd": "ASX.JIN",
    "Nearmap Ltd": "ASX.NEA",
    "Orocobre Ltd": "ASX.ORE",
    "Polynovo Limited": "ASX.PNV",
    "Pushpay Holdings Limited": "ASX.PPH",
    "Qantas Airways Ltd": "ASX.QAN",
    "Santos Ltd": "ASX.STO",
    "SPDR S&P/ASX 200 Fund": "ASX.STW",
    "Transurban Group": "ASX.TCL",
    "Treasury Wine Estates Ltd": "ASX.TWE",
    "Vanguard Australian Shares High Yield ETF": "ASX.VHY",
    "Vanguard Australian Shares Index ETF": "ASX.VAS",
    "Vanguard Diversified Growth Index ETF": "ASX.VDGR",
    "Vanguard MSCI Index International Shares ETF": "ASX.VGS",
    "Vanguard Total Stock Market Index Fund ETF": "NDQ.VTI",
    "Webjet Ltd": "ASX.WEB",
    "Woodside Energy Group Limited": "ASX.WDS",
}