TICKER_MAP = {
    "Afterpay Limited": "APT.AX",
    "Altium Limited": "ALU.AX",
    "Appen Limited": "APX.AX",
    "Arcadium Lithium Plc": "ACY",
    "A2 Milk Co Ltd": "A2M.AX",
    "Bapcor Ltd": "BAP.AX",
    "Betashares Crude Oil Index Etf": "OOO.AX",
    "Betashares Global Sustainability Leaders Etf": "ETHI.AX",
    "Betashares Nasdaq 100 Etf": "NDX.AX",
    "Betashares S&P 500 Yield Maximiser Fund": "UMAX.AX",
    "Betashares Asia Technology Tigers Etf": "ASIA.AX",
    "Betashares Crypto Innovators Etf": "CRYP.AX",
    "Betashares India Quality Etf": "IIND.AX",
    "Blackmores Ltd": "BKL.AX",
    "Block Inc (Au)": "XYZ.AX",
    "Bwx Limited": "BWX.AX",
    "Commonwealth Bank Of Australia": "CBA.AX",
    "Flight Centre Travel Group Ltd": "FLT.AX",
    "Invesco Qqq Trust Series 1 (All Sessions)": "QQQ",
    "Jumbo Interactive Ltd": "JIN.AX",
    "Nearmap Ltd": "NEA.AX",
    "Orocobre Ltd": "ORE.AX",
    "Polynovo Limited": "PNV.AX",
    "Pushpay Holdings Limited": "PPH.AX",
    "Qantas Airways Ltd": "QAN.AX",
    "Santos Ltd": "STO.AX",
    "Spdr S&P/Asx 200 Fund": "STW.AX",
    "Transurban Group": "TCL.AX",
    "Treasury Wine Estates Ltd": "TWE.AX",
    "Vanguard Australian Shares High Yield Etf": "VHY.AX",
    "Vanguard Australian Shares Index Etf": "VAS.AX",
    "Vanguard Diversified Growth Index Etf": "VDGR.AX",
    "Vanguard Msci Index International Shares Etf": "VGS.AX",
    "Vanguard Total Stock Market Index Fund Etf": "VTI",
    "Vanguard Total Stock Market Index Fund Etf Sh Ae - Vti": "VTI",
    "Webjet Ltd": "WEB.AX",
    "Woodside Energy Group Limited": "WDS.AX",
}