NAME_TO_TICKER = {
    "Afterpay Limited": "ASX.APT",
    "Altium Limited": "ASX.ALU",
    "Appen Limited": "ASX.APX",
    "Arcadium Lithium Plc": "NYSE.ACY",
    "A2 Milk Co Ltd": "ASX.A2M",
    "Bapcor Ltd": "ASX.BAP",
    "Betashares Crude Oil Index Etf": "ASX.OOO",
    "Betashares Global Sustainability Leaders Etf": "ASX.ETHI",
    "Betashares Nasdaq 100 Etf": "ASX.NDX",
    "Betashares S&P 500 Yield Maximiser Fund": "ASX.UMAX",
    "Betashares Asia Technology Tigers Etf": "ASX.ASIA",
    "Betashares Crypto Innovators Etf": "ASX.CRYP",
    "Betashares India Quality Etf": "ASX.IIND",
    "Blackmores Limited": "ASX.BKL",
    "Block Inc (Au)": "ASX.XYZ",
    "Bwx Limited": "ASX.BWX",
    "Commonwealth Bank Of Australia": "ASX.CBA",
    "Flight Centre Travel Group Ltd": "ASX.FLT",
    "Invesco Qqq Trust Series 1 (All Sessions)": "NDQ.QQQ",
    "Jumbo Interactive Ltd": "ASX.JIN",
    "Nearmap Ltd": "ASX.NEA",
    "Orocobre Ltd": "ASX.ORE",
    "Polynovo Limited": "ASX.PNV",
    "Pushpay Holdings Limited": "ASX.PPH",
    "Qantas Airways Ltd": "ASX.QAN",
    "Santos Ltd": "ASX.STO",
    "Spdr S&P/Asx 200 Fund": "ASX.STW",
    "Transurban Group": "ASX.TCL",
    "Treasury Wine Estates Ltd": "ASX.TWE",
    "Vanguard Australian Shares High Yield Etf": "ASX.VHY",
    "Vanguard Australian Shares Index Etf": "ASX.VAS",
    "Vanguard Diversified Growth Index Etf": "ASX.VDGR",
    "Vanguard Msci Index International Shares Etf": "ASX.VGS",
    "Vanguard Total Stock Market Index Fund Etf": "NDQ.VTI",
    "Webjet Ltd": "ASX.WEB",
    "Woodside Energy Group Limited": "ASX.WDS",
}